### ISSUE TITLE
# Levantar os requisitos iniciais do sistema

### ISSUE THREAD

**Issue by BrunoSoftbank** [MarioSergio07/Uninove#2]

**Comment by MarioSergio07** [comment]
# O sistema deve permitir o cadastro de perfis de usuário(Admin).
# O sistema deve permitir o cadastro de produto(Admin).
# O sistema deve permitir o cadastro de categorias de produto(Admin).
# O sistema deve permitir que o usuário(cliente), realize um pedido.
# O sistema deve permitir que o usuário(cliente) possa filtrar o produto que deseja visualizar.
# O sistema deve permitir que o usuário(cliente) possa ordenar os resultados da busca por preço menor-maior e maior-menor e por ordem alfabética.
# O sistema deve permitir que ao pedido ser confirmado, seja criada a respectiva venda.
# O sistema deve permitir que a partir do momento que a venda for confirmada, seja disparado um e-mail para o cliente informando os dados da venda.
