### ISSUE TITLE
# Modelar entidades do banco de dados

### ISSUE THREAD

**Issue by BrunoSoftbank** [MarioSergio07/Uninove#7]

**Comment by MarioSergio07** [comment]
![merv2](https://user-images.githubusercontent.com/28636772/45118019-8a7ea380-b12d-11e8-8a02-c102933c5c11.png)

**Comment by MarioSergio07** [comment]
![merv3](https://user-images.githubusercontent.com/28636772/45118453-f1508c80-b12e-11e8-83d8-5800daba778d.png)
